const wordList = [
    { word: "oxygen", hint: "A colorless, odorless gas essential for life." },
    { word: "elephant", hint: "A large mammal with a long trunk and tusks." },
    { word: "planet", hint: "A celestial body that orbits a star." },
    { word: "island", hint: "A piece of land surrounded by water." },
    { word: "telephone", hint: "A communication device used to talk to people at a distance." },
    { word: "spider", hint: "An arachnid with eight legs and often a web-making ability." },
    { word: "jungle", hint: "A dense, tropical forest with a variety of plant and animal life." },
    { word: "submarine", hint: "A watercraft capable of traveling underwater." },
    { word: "clock", hint: "A timekeeping device often found on walls or tables." },
    { word: "astronaut", hint: "A person trained to travel and work in space." },
    { word: "fireworks", hint: "Explosive devices used for entertainment in celebrations." },
    { word: "flag", hint: "A piece of fabric with distinctive colors and designs." },
    { word: "globe", hint: "A spherical representation of the Earth's surface." },
    { word: "honeybee", hint: "An insect that collects nectar to make honey." },
    { word: "ice cream", hint: "A frozen dessert made from dairy products and flavors." },
    { word: "jacket", hint: "An outer garment worn for warmth or style." },
    { word: "kangaroo", hint: "A marsupial with powerful hind legs for jumping." },
    { word: "lighthouse", hint: "A tower with a light to guide ships at sea." },
    { word: "mountain", hint: "A large natural elevation of the Earth's surface." },
    { word: "nest", hint: "A structure built by birds to lay eggs and raise young." },
    { word: "oasis", hint: "A fertile area in a desert with water and vegetation." },
    { word: "parrot", hint: "A colorful bird known for imitating human speech." },
    { word: "queen", hint: "The female ruler of a country or a chess piece." },
    { word: "rainforest", hint: "A dense forest with high rainfall and biodiversity." },
    { word: "sailboat", hint: "A boat propelled by sails." },
    { word: "tiger", hint: "A large carnivorous feline with distinctive stripes." },
    { word: "umbrella", hint: "A portable device used for protection from rain or sun." },
    { word: "volleyball", hint: "A sport played with a ball over a net." },
    { word: "whale", hint: "A large marine mammal inhabiting oceans." }
];